2021-11-20 19:47:48,613 INFO    MainThread:12040 [wandb_setup.py:_flush():71] setting env: {}
2021-11-20 19:47:48,613 INFO    MainThread:12040 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-20 19:47:48,613 INFO    MainThread:12040 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-20 19:47:48,613 INFO    MainThread:12040 [wandb_init.py:_log_setup():371] Logging user logs to d:\Documents\Academics\Fall 2021\TCSS551\Project-1-Titanic-Classification\wandb\run-20211120_194748-1j1dud88\logs\debug.log
2021-11-20 19:47:48,613 INFO    MainThread:12040 [wandb_init.py:_log_setup():372] Logging internal logs to d:\Documents\Academics\Fall 2021\TCSS551\Project-1-Titanic-Classification\wandb\run-20211120_194748-1j1dud88\logs\debug-internal.log
2021-11-20 19:47:48,614 INFO    MainThread:12040 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000204EDF9B400>
2021-11-20 19:47:48,614 INFO    MainThread:12040 [wandb_init.py:init():404] calling init triggers
2021-11-20 19:47:48,614 INFO    MainThread:12040 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2021-11-20 19:47:48,614 INFO    MainThread:12040 [wandb_init.py:init():449] starting backend
2021-11-20 19:47:48,614 INFO    MainThread:12040 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn, using: spawn
2021-11-20 19:47:48,618 INFO    MainThread:12040 [backend.py:ensure_launched():199] starting backend process...
2021-11-20 19:47:48,675 INFO    MainThread:12040 [backend.py:ensure_launched():204] started backend process with pid: 30992
2021-11-20 19:47:48,676 INFO    MainThread:12040 [wandb_init.py:init():458] backend started and connected
2021-11-20 19:47:48,680 INFO    MainThread:12040 [wandb_run.py:_label_probe_notebook():917] probe notebook
2021-11-20 19:47:48,680 INFO    MainThread:12040 [wandb_run.py:_label_probe_notebook():927] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-11-20 19:47:48,680 INFO    MainThread:12040 [wandb_init.py:init():519] updated telemetry
2021-11-20 19:47:48,723 INFO    MainThread:12040 [wandb_init.py:init():549] communicating current version
2021-11-20 19:47:49,968 INFO    MainThread:12040 [wandb_init.py:init():554] got version response 
2021-11-20 19:47:49,968 INFO    MainThread:12040 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-11-20 19:47:50,125 INFO    MainThread:12040 [wandb_init.py:init():592] starting run threads in backend
2021-11-20 19:47:51,856 INFO    MainThread:12040 [wandb_run.py:_console_start():1816] atexit reg
2021-11-20 19:47:51,857 INFO    MainThread:12040 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.WRAP
2021-11-20 19:47:51,857 INFO    MainThread:12040 [wandb_run.py:_redirect():1727] Wrapping output streams.
2021-11-20 19:47:51,858 INFO    MainThread:12040 [wandb_run.py:_redirect():1751] Redirects installed.
2021-11-20 19:47:51,858 INFO    MainThread:12040 [wandb_init.py:init():619] run started, returning control to user process
2021-11-20 19:47:51,860 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 19:47:51,860 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 19:47:51,895 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 19:47:51,896 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 19:47:51,897 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 19:47:51,913 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 19:47:53,108 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 19:47:53,108 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 19:47:53,127 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 19:47:53,136 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 19:47:53,136 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 19:47:53,167 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 19:47:53,169 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 19:47:53,169 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 19:55:17,882 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 19:55:17,884 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 19:55:17,885 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 19:55:27,403 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 19:55:27,405 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 19:55:27,405 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 19:59:58,329 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 19:59:58,340 INFO    MainThread:12040 [wandb_setup.py:_flush():71] setting env: {}
2021-11-20 19:59:58,340 INFO    MainThread:12040 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-20 19:59:58,340 INFO    MainThread:12040 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-20 19:59:58,340 INFO    MainThread:12040 [wandb_init.py:_log_setup():371] Logging user logs to d:\Documents\Academics\Fall 2021\TCSS551\Project-1-Titanic-Classification\wandb\run-20211120_195958-14c1q9v0\logs\debug.log
2021-11-20 19:59:58,340 INFO    MainThread:12040 [wandb_init.py:_log_setup():372] Logging internal logs to d:\Documents\Academics\Fall 2021\TCSS551\Project-1-Titanic-Classification\wandb\run-20211120_195958-14c1q9v0\logs\debug-internal.log
2021-11-20 19:59:58,341 INFO    MainThread:12040 [wandb_init.py:init():404] calling init triggers
2021-11-20 19:59:58,341 INFO    MainThread:12040 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2021-11-20 19:59:58,341 INFO    MainThread:12040 [wandb_init.py:init():424] re-initializing run, found existing run on stack: 1j1dud88
2021-11-20 19:59:58,342 INFO    MainThread:12040 [wandb_run.py:finish():1463] finishing run nclgbd/Titanic-Classification/1j1dud88
2021-11-20 19:59:58,343 ERROR   MainThread:12040 [jupyter.py:save_history():421] Run pip install nbformat to save notebook history
2021-11-20 19:59:58,343 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 19:59:58,343 INFO    MainThread:12040 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2021-11-20 19:59:58,343 INFO    MainThread:12040 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 0
2021-11-20 19:59:58,344 INFO    MainThread:12040 [wandb_run.py:_restore():1758] restore
2021-11-20 19:59:58,935 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1219
  total_bytes: 1219
}

2021-11-20 19:59:59,166 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1219
  total_bytes: 1219
}

2021-11-20 19:59:59,556 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1219
  total_bytes: 7236
}

2021-11-20 19:59:59,659 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1219
  total_bytes: 7236
}

2021-11-20 19:59:59,761 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1219
  total_bytes: 7236
}

2021-11-20 19:59:59,863 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7236
  total_bytes: 7236
}

2021-11-20 19:59:59,965 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7236
  total_bytes: 7236
}

2021-11-20 20:00:00,066 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7236
  total_bytes: 7236
}

2021-11-20 20:00:00,168 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7236
  total_bytes: 7236
}

2021-11-20 20:00:00,269 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7236
  total_bytes: 7236
}

2021-11-20 20:00:00,468 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7236
  total_bytes: 7236
}

2021-11-20 20:00:00,801 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7236
  total_bytes: 7236
}
local_info {
}

2021-11-20 20:00:01,945 INFO    MainThread:12040 [wandb_run.py:_append_files():2184] logging synced files
