2021-11-20 20:33:29,389 INFO    MainThread:12040 [wandb_setup.py:_flush():71] setting env: {}
2021-11-20 20:33:29,389 INFO    MainThread:12040 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-20 20:33:29,389 INFO    MainThread:12040 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-20 20:33:29,389 INFO    MainThread:12040 [wandb_init.py:_log_setup():371] Logging user logs to d:\Documents\Academics\Fall 2021\TCSS551\Project-1-Titanic-Classification\wandb\run-20211120_203329-3tm0x3qt\logs\debug.log
2021-11-20 20:33:29,389 INFO    MainThread:12040 [wandb_init.py:_log_setup():372] Logging internal logs to d:\Documents\Academics\Fall 2021\TCSS551\Project-1-Titanic-Classification\wandb\run-20211120_203329-3tm0x3qt\logs\debug-internal.log
2021-11-20 20:33:29,390 INFO    MainThread:12040 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000204F31D1840>
2021-11-20 20:33:29,390 INFO    MainThread:12040 [wandb_init.py:init():404] calling init triggers
2021-11-20 20:33:29,390 INFO    MainThread:12040 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2021-11-20 20:33:29,390 INFO    MainThread:12040 [wandb_init.py:init():449] starting backend
2021-11-20 20:33:29,390 INFO    MainThread:12040 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=spawn, using: spawn
2021-11-20 20:33:29,393 INFO    MainThread:12040 [backend.py:ensure_launched():199] starting backend process...
2021-11-20 20:33:29,453 INFO    MainThread:12040 [backend.py:ensure_launched():204] started backend process with pid: 28540
2021-11-20 20:33:29,454 INFO    MainThread:12040 [wandb_init.py:init():458] backend started and connected
2021-11-20 20:33:29,455 INFO    MainThread:12040 [wandb_run.py:_label_probe_notebook():917] probe notebook
2021-11-20 20:33:29,455 INFO    MainThread:12040 [wandb_run.py:_label_probe_notebook():927] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-11-20 20:33:29,456 INFO    MainThread:12040 [wandb_init.py:init():519] updated telemetry
2021-11-20 20:33:29,487 INFO    MainThread:12040 [wandb_init.py:init():549] communicating current version
2021-11-20 20:33:30,826 INFO    MainThread:12040 [wandb_init.py:init():554] got version response 
2021-11-20 20:33:30,826 INFO    MainThread:12040 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-11-20 20:33:31,032 INFO    MainThread:12040 [wandb_init.py:init():592] starting run threads in backend
2021-11-20 20:33:32,817 INFO    MainThread:12040 [wandb_run.py:_console_start():1816] atexit reg
2021-11-20 20:33:32,818 INFO    MainThread:12040 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.WRAP
2021-11-20 20:33:32,818 INFO    MainThread:12040 [wandb_run.py:_redirect():1727] Wrapping output streams.
2021-11-20 20:33:32,819 INFO    MainThread:12040 [wandb_run.py:_redirect():1751] Redirects installed.
2021-11-20 20:33:32,819 INFO    MainThread:12040 [wandb_init.py:init():619] run started, returning control to user process
2021-11-20 20:33:32,821 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 20:33:32,821 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 20:33:32,837 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 20:33:32,838 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 20:33:32,838 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 20:33:32,857 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 20:33:32,869 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 20:33:32,869 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 20:33:32,890 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 20:33:32,905 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 20:33:32,906 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 20:34:04,533 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 20:34:04,548 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 20:34:04,548 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 20:34:15,408 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 20:34:15,409 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 20:34:15,409 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 20:34:17,936 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 20:34:17,947 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 20:34:17,947 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 20:34:22,341 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 20:34:22,341 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 20:34:22,342 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 20:34:23,765 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 20:34:23,770 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 20:34:23,770 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 20:34:26,443 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 20:34:26,445 INFO    MainThread:12040 [wandb_init.py:_pause_backend():284] pausing backend
2021-11-20 20:34:26,445 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 20:34:30,006 INFO    MainThread:12040 [wandb_init.py:_resume_backend():293] resuming backend
2021-11-20 20:34:30,014 INFO    MainThread:12040 [wandb_run.py:finish():1463] finishing run nclgbd/Titanic-Classification/3tm0x3qt
2021-11-20 20:34:30,015 ERROR   MainThread:12040 [jupyter.py:save_history():421] Run pip install nbformat to save notebook history
2021-11-20 20:34:30,015 INFO    MainThread:12040 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-11-20 20:34:30,015 INFO    MainThread:12040 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2021-11-20 20:34:30,015 INFO    MainThread:12040 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 1
2021-11-20 20:34:30,015 INFO    MainThread:12040 [wandb_run.py:_restore():1758] restore
2021-11-20 20:34:30,909 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1219
  total_bytes: 1219
}

2021-11-20 20:34:31,148 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1219
  total_bytes: 1219
}

2021-11-20 20:34:32,094 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1219
  total_bytes: 7790
}

2021-11-20 20:34:32,195 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1219
  total_bytes: 7790
}

2021-11-20 20:34:32,296 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1219
  total_bytes: 7790
}

2021-11-20 20:34:32,398 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7790
  total_bytes: 7790
}

2021-11-20 20:34:32,499 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7790
  total_bytes: 7790
}

2021-11-20 20:34:32,601 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7790
  total_bytes: 7790
}

2021-11-20 20:34:32,702 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7790
  total_bytes: 7790
}

2021-11-20 20:34:32,963 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7790
  total_bytes: 7790
}

2021-11-20 20:34:33,309 INFO    MainThread:12040 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 7790
  total_bytes: 7790
}
local_info {
}

2021-11-20 20:34:34,435 INFO    MainThread:12040 [wandb_run.py:_append_files():2184] logging synced files
